name: Build APT Repo
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Packages
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages

      - name: Commit & Push
        run: |
          git config user.name "actions-bot"
          git config user.email "bot@github.com"
          git add Packages Packages.gz
          git commit -m "auto update repo index" || echo "No changes"
          git push