name: Build APT Repo
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate APT Packages index
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.gz
          git commit -m "Auto update repo index" || echo "No changes to commit"
          git push