name: Build APT Repo
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dpkg-dev
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Generate Packages index
        run: |
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages

      - name: Commit & Push index files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          git add Packages Packages.gz
          git commit -m "Auto update apt index" || echo "No changes to commit"
          git push